/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4l6fopdwynclza7oorubw3vupq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ovn6jay6hjhurpwa5krlm3i2aa",
    "aws_cognito_identity_pool_id": "us-east-1:cfc8d4e7-0cac-47da-ac15-1ea9080ab2c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4mrPFECeo",
    "aws_user_pools_web_client_id": "7s33hdkeq5qnjmgga1rpdc9a2t",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "map379bcbba-dev": {
                        "style": "VectorEsriStreets"
                    },
                    "map081d68c7-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "map081d68c7-dev"
            }
        }
    }
};


export default awsmobile;
